### ISSUE TITLE
Checkpoint 1: Trek Roulette ready for review

### ISSUE THREAD

**Issue by tmirkes** [tmirkes/TrekRoulette#1]
@pawaitemadisoncollege Trek Roulette checkpoint 1 is ready for your review.

I'm looking forward to your feedback on the design documents.  This is the first software project for which I've been responsible for the whole gamut of documents ahead of actually doing the coding, so I'm anxious to hear what I've done right and where I can shore up my work.

For my part, I'm most uncertain about the project plan.  I hit a wall and couldn't really think of any major milestones that would still be required, and I was only at week 10.  I'm absolutely certain my inexperience at estimating project time and either overestimating the time I'll have or underestimating the time the tasks will take means I've got all the pieces, just too condensed to be realistic.

In any case, I'm looking forward to hearing what you've got for me.  Let me know if you'd like to do a live code review; if that's easier for you than typing a bunch, let me know.  Most afternoons are flexible for me.

**Comment by pawaitemadisoncollege** [comment]
Hi @tmirkes! This is such a fun and unique project. It seems like there's some good opportunity to do some fun logic in episode selection algorithm if you want to head down that path!

**Problem statement** does a good job explaining the problem and the high-level solution. 

**Technologies** looks to be a solid start. Be sure to update what tech is actually used in the final product.

**User stories** On thing I like to consider here is that the project requirements are met with the MVP. One that I think may be missing is a delete scenario? Is there a meaningful story that you could add to cover the delete? If not, you could demonstrate this proficiency in another way of your choice.

**Project plan** Very thorough! 

- [ ] I think you may be able to remove (good news right?!) some tasks - for example the entity-specific DAOs. The single "generic" dao should be able to meet the needs of all entities/tables (I introduce this in week 5)! 
- [ ] Might consider documenting a plan for regularly deploying to AWS. 
- [ ] Weeks 9-12 tend to get very busy with the Team Project, so you may find time spend on the indie project in this timeframe is reduced. 
- [ ] In week 6 and 14 you'll be conducting  peer reviews - might be worth noting here and adding one or more tasks for incorporating feedback from those reviews. 
- [ ] Similar comment as above for checkpoints. 
- [ ] I don't think I saw tasks for building the DAO that will access the api/s and testing thereof?

**Flow and Screens** Very thorough - it's clear you put some good time and thought into this and that will pay off as you build this out! 

- [ ] We'll be using AWS Cognito for user registration and authentication so your flow and some tasks might be reduced :) Watch for that in week 7.

**Database ERD** While not required at this point, if you have it ready, it might be helpful to those reviewing your project to be able to see that design sooner than later. You can use whatever tool you like for this, but know that you can generate an ERD in IntelliJ from the database view.
